
services:
  web:
    container_name: web
    build: .
    command: npm start
    ports:
      - ${EZD_API_PORT}:${EZD_API_PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${EZD_API_PORT}
  postgres:
    container_name: postgres_db
    restart: unless-stopped
    # platform: linux/amd64
    # image: postgres:latest
    build:
      dockerfile: ./Dockerfile.pg
    ports: 
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./ezd_api_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

