
export enum EXIT_SIGNAL_CODE_ENUM {
  SIGINT = 'SIGINT',
  SIGTERM = 'SIGTERM',
  SIGQUIT = 'SIGQUIT',
}

export const EXIT_SIGNAL_CODES = [
  EXIT_SIGNAL_CODE_ENUM.SIGINT,
  EXIT_SIGNAL_CODE_ENUM.SIGTERM,
  EXIT_SIGNAL_CODE_ENUM.SIGQUIT,
];

export const PASSWORD_HASH_ITERATIONS = 1e5;
export const PASSWORD_HASH_KEYLEN = 64;
export const PASSWORD_HASH_ALGO = 'sha512';
