
export enum EXIT_SIGNAL_CODE_ENUM {
  SIGINT = 'SIGINT',
  SIGTERM = 'SIGTERM',
  SIGQUIT = 'SIGQUIT',
}

export const EXIT_SIGNAL_CODES = [
  EXIT_SIGNAL_CODE_ENUM.SIGINT,
  EXIT_SIGNAL_CODE_ENUM.SIGTERM,
  EXIT_SIGNAL_CODE_ENUM.SIGQUIT,
];
